module.exports ={
	DATABASE_HOST:process.env.DATABASE_HOST,
	DATABASE_USER:process.env.DATABASE_USER,
	DATABASE_SECRET: process.env.DATABASE_SECRET,
	DATABASE_NAME:process.env.DATABASE_NAME,
	DATABASE_PORT: process.env.DATABASE_PORT
}